spring:
  application:
    name: community-spring
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: tr
        use_sql_comments: true
springdoc:
  default-produces-media-type: application/json
logging:
  level:
    org:
      springframework:
        jdbc: debug
      school:
        kakao:
          communityspring: debug
      hibernate:
        type:
          descriptor:
            sql: trace