spring:
  application:
    name: community-spring
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        jdbc: debug
      school:
        kakao:
          communityspring: debug