name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment: dev
    env:
      AWS_REGION: 'ap-northeast-2'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Configuration for AWS
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: community-api
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./Dockerfile
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG